source 'https://cdn.cocoapods.org'

# ignore all warnings from all pods
# inhibit_all_warnings!

platform :ios, '14.1'

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#     end
#   end
# end

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
# need for correct invalidate of cache shared.framework
install! 'cocoapods', :disable_input_output_paths => true

target 'iosApp' do
        pod 'shared', :path => '../shared'
        pod 'sharedOrbitSwift', :path => '../shared'
end
